<option value="Abay Bank"> Abay Bank </option>
<option value="Addis Bank SC"> Addis Bank SC </option>
<option value="Awash International Bank"> Awash International Bank </option>
<option value="Bank of Abyssinia"> Bank of Abyssinia </option>
<option value="Berhan International Bank"> Berhan International Bank </option>
<option value="Bunna International Bank"> Bunna International Bank </option>
<option value="Commerical Bank of Ethiopia"> Commerical Bank of Ethiopia </option>
<option value="Cooperative Bank of Oromia"> Cooperative Bank of Oromia </option>
<option value="Dashen Bank"> Dashen Bank </option>
<option value="Debub Global Bank"> Debub Global Bank </option>
<option value="Development Bank of Ethiopia"> Development Bank of Ethiopia </option>
<option value="Enat Bank"> Enat Bank </option>
<option value="Lion International Bank"> Lion International Bank </option>
<option value="Nib International Bank"> Nib International Bank </option>
<option value="Oromia International Bank"> Oromia International Bank </option>
<option value="United Bank"> United Bank </option>
<option value="Wegagen Bank"> Wegagen Bank </option>
<option value="ZamZam Bank"> ZamZam Bank </option>
<option value="Zemen Bank"> Zemen Bank </option>
