<option value="Telebirr"> Telebirr </option>
<option value="M-Pesa"> M-Pesa </option>
<option value="Abay Bank"> Abay Bank </option>
<option value="Addis Bank SC"> Addis Bank SC </option>
<option value="Ahadu Bank"> Ahadu Bank </option>
<option value="Amhara Bank"> Amhara Bank </option>
<option value="Awash International Bank"> Awash International Bank </option>
<option value="Bank of Abyssinia"> Bank of Abyssinia </option>
<option value="Berhan International Bank"> Berhan International Bank </option>
<option value="Bunna International Bank"> Bunna International Bank </option>
<option value="Commerical Bank of Ethiopia"> Commerical Bank of Ethiopia </option>
<option value="Cooperative Bank of Oromia"> Cooperative Bank of Oromia </option>
<option value="Dashen Bank"> Dashen Bank </option>
<option value="Debub Global Bank"> Debub Global Bank </option>
<option value="Development Bank of Ethiopia"> Development Bank of Ethiopia </option>
<option value="Enat Bank"> Enat Bank </option>
<option value="Gadaa Bank SC"> Gadaa Bank SC </option>
<option value="Goh Betoch Bank SC"> Goh Betoch Bank SC </option>
<option value="Hijra Bank"> Hijra Bank </option>
<option value="Lion International Bank"> Lion International Bank </option>
<option value="National Bank of Ethiopia"> National Bank of Ethiopia </option>
<option value="Nib International Bank"> Nib International Bank </option>
<option value="Oromia International Bank"> Oromia International Bank </option>
<option value="Siinqee Bank"> Siinqee Bank </option>
<option value="Tsedey Bank"> Tsedey Bank </option>
<option value="Tsehay Bank"> Tsehay Bank </option>
<option value="United (Hibret) Bank"> United (Hibret) Bank </option>
<option value="Wegagen Bank"> Wegagen Bank </option>
<option value="ZamZam Bank"> ZamZam Bank </option>
<option value="Zemen Bank"> Zemen Bank </option>
