<option value="Adama">Adama</option>
<option value="Addis Ababa">Addis Ababa</option>
<option value="Arba Minch">Arba Minch</option>
<option value="Assela">Assela</option>
<option value="Awasa">Awasa</option>
<option value="Bahir Dar">Bahir Dar</option>
<option value="Bishoftu">Bishoftu</option>
<option value="Debre Birhan">Debre Birhan</option>
<option value="Debre Markos">Debre Markos</option>
<option value="Dessie">Dessie</option>
<option value="Dire Dawa">Dire Dawa</option>
<option value="Gonder">Gonder</option>
<option value="Harar">Harar</option>
<option value="Hosaena">Hosaena</option>
<option value="Jijiga">Jijiga</option>
<option value="Jimma">Jimma</option>
<option value="Mekele">Mekele</option>
<option value="Mojo">Mojo</option>
<option value="Shashemene">Shashemene</option>
<option value="Wolayta">Wolayta</option>